# Regressão Logística

In [11]:
from sklearn.linear_model import LogisticRegression

### Base Risco Crédito

In [6]:
import pickle
import numpy as np

with open('/content/drive/MyDrive/Machine Learning/Classificação/risco_credito.pkl', 'rb') as f:
  X_risco_credito, y_risco_credito = pickle.load(f)

In [8]:
# Apagar os valores 'moderados'
X_risco_credito = np.delete(X_risco_credito, [2,7,11], axis=0)
y_risco_credito = np.delete(y_risco_credito, [2,7,11], axis=0)

In [14]:
logistic_risco_credito = LogisticRegression(random_state=1)
logistic_risco_credito.fit(X_risco_credito, y_risco_credito)

LogisticRegression(random_state=1)

In [15]:
logistic_risco_credito.intercept_

array([-0.80828993])

In [16]:
logistic_risco_credito.coef_

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [19]:
previsoes_risco = logistic_risco_credito.predict([[0,0,1,2],[2,0,0,0]])
previsoes_risco

array(['baixo', 'alto'], dtype=object)

### Base Credit

In [32]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
import numpy as np
from sklearn.linear_model import LogisticRegression

with open('/content/drive/MyDrive/Machine Learning/Classificação/credit.pkl', 'rb') as f:
  X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

In [24]:
logistic_credit = LogisticRegression(random_state=0)
logistic_credit.fit(X_credit_treinamento,y_credit_treinamento)

LogisticRegression(random_state=0)

In [27]:
logistic_credit.intercept_

array([-6.02976095])

In [28]:
logistic_credit.coef_

array([[-2.54927091, -3.72279861,  3.93940349]])

In [33]:
previsoes_credit = logistic_credit.predict(X_credit_teste)

In [35]:
from sklearn.metrics import accuracy_score, classification_report
accuracy_score(y_credit_teste,previsoes_credit)

0.946

### Base Census

In [36]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
import numpy as np

with open('/content/drive/MyDrive/Machine Learning/Classificação/census.pkl', 'rb') as f:
  X_census_treinamento, y_census_treinamento, X_census_teste, y_census_teste = pickle.load(f)

In [37]:
logistic_census = LogisticRegression(random_state=0)
logistic_census.fit(X_census_treinamento,y_census_treinamento)

LogisticRegression(random_state=0)

In [38]:
previsoes_census = logistic_census.predict(X_census_teste)

In [39]:
accuracy_score(y_census_teste,previsoes_census)

0.849539406345957