In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import cross_val_score, KFold

In [3]:
import pickle

with open('/content/drive/MyDrive/Machine Learning/Download/Bases de dados/credit.pkl', 'rb') as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

In [4]:
X_credit = np.concatenate((X_credit_treinamento,X_credit_teste),axis=0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis=0)

In [5]:
resultados_knn= []

for i in range(30):
    kfold = KFold(n_splits=10, shuffle=True, random_state=i)

    arvore = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=1, min_samples_split=5,splitter='best')
    scores = cross_val_score(arvore, X_credit, y_credit, cv=kfold)
    print(scores)

[0.995 0.98  0.985 0.985 0.98  0.995 0.98  0.98  0.985 0.995]
[0.995 0.98  0.985 0.985 0.985 0.965 0.99  0.99  0.98  0.985]
[0.99  0.99  0.99  0.98  0.995 1.    0.99  0.99  0.99  0.99 ]
[0.98  0.98  0.98  0.99  0.965 1.    1.    0.985 0.99  1.   ]
[1.    0.995 0.97  0.995 0.99  0.995 0.985 0.98  0.98  1.   ]
[0.985 0.99  0.99  0.995 0.99  0.985 0.995 0.99  0.99  0.975]
[0.985 1.    0.99  0.985 0.99  0.995 0.985 0.975 0.99  0.99 ]
[0.99  0.985 0.995 0.98  0.99  0.985 0.995 0.975 0.99  0.99 ]
[1.    0.98  0.995 0.985 0.99  0.975 0.99  0.98  0.98  0.98 ]
[0.99  0.99  0.995 0.985 0.965 0.99  0.995 0.975 0.995 0.99 ]
[0.99  0.985 0.995 0.975 1.    0.99  0.99  0.98  0.99  0.97 ]
[1.    0.99  0.985 0.99  0.985 0.985 0.98  0.98  1.    1.   ]
[0.995 0.98  0.995 0.99  0.995 0.995 0.995 0.975 0.98  0.985]
[0.99  0.99  0.995 0.995 0.97  0.995 0.98  0.985 0.99  0.98 ]
[0.985 0.99  0.995 0.985 0.985 0.99  0.97  0.98  0.99  0.98 ]
[1.    0.985 0.99  0.965 0.99  0.975 0.99  0.98  0.99  0.985]
[0.99  0